export const SQL_KEYWORDS = {
    /**
     * Reserved SQL keywords based on SQL-92 standard
     * {@link https://www.sqlite.org/lang_keywords.html}
     */
    ABORT: 'ABORT',
    ACTION: 'ACTION',
    ADD: 'ADD',
    AFTER: 'AFTER',
    ALL: 'ALL',
    ALTER: 'ALTER',
    ALWAYS: 'ALWAYS',
    ANALYZE: 'ANALYZE',
    AND: 'AND',
    ANY: 'ANY',
    AS: 'AS',
    ASC: 'ASC',
    ATTACH: 'ATTACH',
    AUTOINCREMENT: 'AUTOINCREMENT',
    BEFORE: 'BEFORE',
    BEGIN: 'BEGIN',
    BETWEEN: 'BETWEEN',
    BY: 'BY',
    CASCADE: 'CASCADE',
    CASE: 'CASE',
    CAST: 'CAST',
    CHECK: 'CHECK',
    COLLATE: 'COLLATE',
    COLUMN: 'COLUMN',
    COMMIT: 'COMMIT',
    CONFLICT: 'CONFLICT',
    CONSTRAINT: 'CONSTRAINT',
    CREATE: 'CREATE',
    CROSS: 'CROSS',
    CURRENT: 'CURRENT',
    CURRENT_DATE: 'CURRENT_DATE',
    CURRENT_TIME: 'CURRENT_TIME',
    CURRENT_TIMESTAMP: 'CURRENT_TIMESTAMP',
    DATABASE: 'DATABASE',
    DEFAULT: 'DEFAULT',
    DEFERRABLE: 'DEFERRABLE',
    DEFERRED: 'DEFERRED',
    DELETE: 'DELETE',
    DESC: 'DESC',
    DETACH: 'DETACH',
    DISTINCT: 'DISTINCT',
    DO: 'DO',
    DROP: 'DROP',
    EACH: 'EACH',
    ELSE: 'ELSE',
    END: 'END',
    ESCAPE: 'ESCAPE',
    EXCEPT: 'EXCEPT',
    EXCLUDE: 'EXCLUDE',
    EXCLUSIVE: 'EXCLUSIVE',
    EXISTS: 'EXISTS',
    EXPLAIN: 'EXPLAIN',
    FAIL: 'FAIL',
    FILTER: 'FILTER',
    FIRST: 'FIRST',
    FOLLOWING: 'FOLLOWING',
    FOR: 'FOR',
    FOREIGN: 'FOREIGN',
    FROM: 'FROM',
    FULL: 'FULL',
    GENERATED: 'GENERATED',
    GLOB: 'GLOB',
    GROUP: 'GROUP',
    GROUPS: 'GROUPS',
    HAVING: 'HAVING',
    IF: 'IF',
    IGNORE: 'IGNORE',
    IMMEDIATE: 'IMMEDIATE',
    IN: 'IN',
    INDEX: 'INDEX',
    INDEXED: 'INDEXED',
    INITIALLY: 'INITIALLY',
    INNER: 'INNER',
    INSERT: 'INSERT',
    INSTEAD: 'INSTEAD',
    INTERSECT: 'INTERSECT',
    INTO: 'INTO',
    IS: 'IS',
    ISNULL: 'ISNULL',
    JOIN: 'JOIN',
    KEY: 'KEY',
    LAST: 'LAST',
    LEFT: 'LEFT',
    LIKE: 'LIKE',
    LIMIT: 'LIMIT',
    MATCH: 'MATCH',
    MATERIALIZED: 'MATERIALIZED',
    NATURAL: 'NATURAL',
    NO: 'NO',
    NOT: 'NOT',
    NOTHING: 'NOTHING',
    NOTNULL: 'NOTNULL',
    NULL: 'NULL',
    NULLS: 'NULLS',
    OF: 'OF',
    OFFSET: 'OFFSET',
    ON: 'ON',
    OR: 'OR',
    ORDER: 'ORDER',
    OTHERS: 'OTHERS',
    OUTER: 'OUTER',
    OVER: 'OVER',
    PARTITION: 'PARTITION',
    PLAN: 'PLAN',
    PRAGMA: 'PRAGMA',
    PRECEDING: 'PRECEDING',
    PRIMARY: 'PRIMARY',
    QUERY: 'QUERY',
    RAISE: 'RAISE',
    RANGE: 'RANGE',
    RECURSIVE: 'RECURSIVE',
    REFERENCES: 'REFERENCES',
    REGEXP: 'REGEXP',
    REINDEX: 'REINDEX',
    RELEASE: 'RELEASE',
    RENAME: 'RENAME',
    REPLACE: 'REPLACE',
    RESTRICT: 'RESTRICT',
    RETURNING: 'RETURNING',
    RIGHT: 'RIGHT',
    ROLLBACK: 'ROLLBACK',
    ROW: 'ROW',
    ROWS: 'ROWS',
    SAVEPOINT: 'SAVEPOINT',
    SELECT: 'SELECT',
    SET: 'SET',
    TABLE: 'TABLE',
    TEMP: 'TEMP',
    TEMPORARY: 'TEMPORARY',
    THEN: 'THEN',
    TIES: 'TIES',
    TO: 'TO',
    TRANSACTION: 'TRANSACTION',
    TRIGGER: 'TRIGGER',
    UNBOUNDED: 'UNBOUNDED',
    UNION: 'UNION',
    UNIQUE: 'UNIQUE',
    UPDATE: 'UPDATE',
    USING: 'USING',
    VACUUM: 'VACUUM',
    VALUES: 'VALUES',
    VIEW: 'VIEW',
    VIRTUAL: 'VIRTUAL',
    WHEN: 'WHEN',
    WHERE: 'WHERE',
    WINDOW: 'WINDOW',
    WITH: 'WITH',
    WITHOUT: 'WITHOUT',

    /**
     * Built-in SQL aggregate functions
     * {@link https://sqlite.org/lang_aggfunc.html}
     */
    AVG: 'AVG',
    COUNT: 'COUNT',
    MAX: 'MAX',
    MIN: 'MIN',
    SUM: 'SUM',
} as const

export type SqlKeyword = typeof SQL_KEYWORDS[keyof typeof SQL_KEYWORDS]

export const SQL_SYMBOLS = {
    ALL: '*',
    EQ: '=',
    NE: '!=',
    GT: '>',
    GE: '>=',
    LT: '<',
    LE: '<=',
    LPAREN: '(',
    RPAREN: ')',
    COMMA: ',',
    DOT: '.',
    SEMI: ';',
} as const

export type SqlSymbol = typeof SQL_SYMBOLS[keyof typeof SQL_SYMBOLS]
